id: opecha:P008083
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17599
  title: དཔལ་ས་སྐྱའི་འཁོན་གདུང་འཇིག་མེད་རྡོ་རྗེ་རིན་པོ་ཆེའི་ཞབས་བརྟན་རྡོ་རྗེའི་སྒྲ་དབྱངས་སོགས།
  volume: ''
  author: ''
