id: opecha:P008083
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17599
  title: དཔལ་ས་སྐྱའི་འཁོན་གདུང་འཇིག་མེད་རྡོ་རྗེ་རིན་པོ་ཆེའི་ཞབས་བརྟན་རྡོ་རྗེའི་སྒྲ་དབྱངས་སོགས།
  volume:
    f937e352e7de44bd83ab10251bf56308:
      image_group_id: I1KG17989
      title: Volume 1 of dpal sa skya'i 'khon gdung 'jig med rdo rje rin po che'i
        zhabs brtan rdo rje'i sgra dbyangs/
      volume_number: 1
      total_pages: 104
  author: ''
ebook_metadata:
  title: དཔལ་ས་སྐྱའི་འཁོན་གདུང་འཇིག་མེད་རྡོ་རྗེ་རིན་པོ་ཆེའི་ཞབས་བརྟན་རྡོ་རྗེའི་སྒྲ་དབྱངས་སོགས།
  author: ''
  sku: P008083
  cover: cover.jpg
  layers:
  - pagination
