id: P008083
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17599
  title: དཔལ་ས་སྐྱའི་འཁོན་གདུང་འཇིག་མེད་རྡོ་རྗེ་རིན་པོ་ཆེའི་ཞབས་བརྟན་རྡོ་རྗེའི་སྒྲ་དབྱངས་སོགས།
  author: ''
  volumes:
    b68b310d811d49a98a644c07f30158f5:
      image_group_id: I1KG17989
      title: ''
      volume_number: 1
      total_pages: 104
ebook_metadata:
  title: དཔལ་ས་སྐྱའི་འཁོན་གདུང་འཇིག་མེད་རྡོ་རྗེ་རིན་པོ་ཆེའི་ཞབས་བརྟན་རྡོ་རྗེའི་སྒྲ་དབྱངས་སོགས།
  author: ''
  sku: P008083
  cover: cover.jpg
  layers:
  - pagination
